name: Wisemind Full Auto Deploy

on:
  push:
    branches: [master, main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 소스코드
        uses: actions/checkout@v3

      - name: SSH 설정
        run: |
          mkdir -p ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: 서버 원격 배포 실행
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} "
            cd /home/ubuntu/wisemind-server &&
            git pull origin main &&
            docker-compose down &&
            docker-compose build &&
            docker-compose up -d
          "
